---
- hosts: servers
  become: true
  tasks:
    - name: "Install git"
      apt:
        name: git
        state: present
        update_cache: yes
    - name: "Clone Config"
      git:
        repo: 
        dest: /home/config/
        clone: yes
        update: yes
    - name: "Execute the script"
      command: sh /home/config/config.sh
      fd
