---
- hosts: first-group
  become: true
  gather_facts: false
  vars:
    users:
      - name: mohammad
        password: password1
        ssh_key: "key"

      - name: support
        password: password2
        ssh_key: "key"
  tasks:
  - name: "make direcotry"
    file:
      path: "/user_home"
      state: directory
  - name: "Create users"
    user:
      name: "{{ item.name }}"
      password: "{{ item.password }}" 
      groups: "admin,www-data" # az tools negah shavad
      append: yes
      state: present
      shell: /bin/bash
      createhome: yes
      home: "/user_home/{{ item.name }}"
      update_password: on_create      
    with_items: "{{ users }}"
  - name: "make direcotry"
    file:
      path: "/user_home/{{ item.name }}/.ssh"
      state: directory
    with_items: "{{ users }}"
  - name: "create empty file"
    file:
      path: "/home/{{ item.name }}/.ssh/authorized_keys"
      state: touch
    with_items: "{{ users }}"
  - name: "put pubkey for users"
    lineinfile:
      path: "/home/{{ item.name}}/.ssh/authorized_keys"
      line: "{{ item.ssh_key }}"
    with_items: "{{ users }}"

  #   - name: Disable Root Login
  #    lineinfile:
  #          dest=/etc/ssh/sshd_config
  #          regexp='^PermitRootLogin'
  #          line="PermitRootLogin no"
  #          state=present
  #          backup=yes
  #    notify:
  #      - restart ssh
  #  handlers:
  #  - name: restart ssh
  #    service:
  #      name=sshd
  #      state=restarted 