---
- hosts: all
  become: true
  gather_facts: false
  vars:
    users:
      - name: name 1
        password: pass
        ssh_key: ""

      - name: name 2
        password: pass
        ssh_key: ""

  tasks:
  - name: "make direcotry"
    file:
      path: "/user_home/{{ item.name }}"
      state: directory
    with_items: "{{ users }}"

  - name: "Create users"
    user:
      name: "{{ item.name }}"
      password: "{{ item.password | password_hash('sha512') }}"
      state: present
      shell: /bin/bash
      createhome: yes
      home: "/user_home/{{ item.name }}"
      update_password: on_create      
    with_items: "{{ users }}"

  - name: "make direcotry"
    file:
      path: "/user_home/{{ item.name }}/.ssh"
      state: directory
      mode: 0751
    with_items: "{{ users }}"

  - name: "create empty file"
    file:
      path: "/user_home/{{ item.name }}/.ssh/authorized_keys"
      state: touch
      mode: 0644
    with_items: "{{ users }}"

  - name: "put pubkey for users"
    lineinfile: 
      path: "/user_home/{{ item.name }}/.ssh/authorized_keys"
      line: "{{ item.ssh_key }}"
    with_items: "{{ users }}"

  - name: "Allow sudo for users"
    copy:
      content: "{{ item.name }} ALL=(ALL) ALL"
      dest: "/etc/sudoers.d/{{ item.name }}"
      mode: 0600
    with_items: "{{ users }}"

  - name: "Max auth check"
    lineinfile: 
      dest: "/etc/ssh/sshd_config"
      regexp: '^MaxAuthTries'
      line: 'MaxAuthTries 30'
      state: present

  - name: "disable empty password"
    lineinfile: 
      dest: "/etc/ssh/sshd_config"
      regexp: '^PermitEmptyPasswords'
      line: 'PermitEmptyPasswords no'
      state: present

  - name: "disable kerberos auth"
    lineinfile: 
      dest: "/etc/ssh/sshd_config"
      regexp: '^KerberosAuthentication'
      line: 'KerberosAuthentication no'
      state: present

  - name: "disable gssapi auth"
    lineinfile: 
      dest: "/etc/ssh/sshd_config"
      regexp: '^GSSAPIAuthentication'
      line: 'GSSAPIAuthentication no'
      state: present

  - name: "enable pubkey auth"
    lineinfile:
      dest: "/etc/ssh/sshd_config"
      regexp: '^PubkeyAuthentication'
      line: 'PubkeyAuthentication yes'
      state: present

    notify:
      - restart ssh
      
  handlers:
   - name: restart ssh
     service:
       name: sshd
       state: restarted