---
- hosts: all
  become: true
  gather_facts: false
  vars:
    users:
      - name: user-1
        password: "password"
        ssh_key: "ssh-key"

      - name: user-2
        password: "password"
        ssh_key: "ssh-key"

  tasks:
  - name: "make direcotry"
    file:
      path: "/user_home/{{ item.name }}"
      state: directory
    with_items: "{{ users }}"

  - name: "Create users"
    user:
      name: "{{ item.name }}"
      password: "{{ item.password | password_hash('sha512') }}"
      groups: "root"
      append: yes
      state: present
      shell: /bin/bash
      createhome: yes
      home: "/user_home/{{ item.name }}"
      update_password: on_create      
    with_items: "{{ users }}"

  - name: "make direcotry for sudoers"
    file:
      path: "/etc/sudoers.d/{{ item.name }}"
      state: touch
    with_items: "{{ users }}"    

  - name: "Add sudo privileges to specified users"
    lineinfile:
      path: "/etc/sudoers.d/{{ item.name }}"
      line: "{{ item.name }} ALL=(ALL) ALL"
    with_items: "{{ users }}"

  - name: "make direcotry"
    file:
      path: "/user_home/{{ item.name }}/.ssh"
      state: directory
    with_items: "{{ users }}"

  - name: "create empty file"
    file:
      path: "/user_home/{{ item.name }}/.ssh/authorized_keys"
      state: touch
    with_items: "{{ users }}"

  - name: "put pubkey for users"
    lineinfile:
      path: "/user_home/{{ item.name}}/.ssh/authorized_keys"
      line: "{{ item.ssh_key }}"
    with_items: "{{ users }}"

  - name: "Disable Root Login"
    lineinfile:
      dest: "/etc/ssh/sshd_config"
      regexp: '^PermitRootLogin'
      line: "PermitRootLogin no"
      state: present
      backup: yes

  - name: "add MaxAuthTries"
    lineinfile:
      dest: "/etc/ssh/sshd_config"
      regexp: '^MaxAuthTries'
      line: "MaxAuthTries 30"
      state: present

  - name: "add PermitEmptyPasswords"
    lineinfile:
      dest: "/etc/ssh/sshd_config"
      regexp: '^PermitEmptyPasswords'
      line: "PermitEmptyPasswords no"
      state: present

  - name: "add KerberosAuthentication"
    lineinfile:
      dest: "/etc/ssh/sshd_config"
      regexp: '^KerberosAuthentication'
      line: "KerberosAuthentication no"
      state: present

  - name: "add GSSAPIAuthentication"
    lineinfile:
      dest: "/etc/ssh/sshd_config"
      regexp: '^GSSAPIAuthentication'
      line: "GSSAPIAuthentication no"
      state: present

  - name: "add PubkeyAuthentication"
    lineinfile:
      dest: "/etc/ssh/sshd_config"
      regexp: '^PubkeyAuthentication'
      line: "PubkeyAuthentication yes"
      state: present

  - name: "Disable password login"
    lineinfile: 
      dest: "/etc/ssh/sshd_config"
      regexp: '^(#\s*)?PasswordAuthentication'
      line: 'PasswordAuthentication no'
    notify:
      - restart ssh
      
  handlers:
   - name: restart ssh
     service:
       name: sshd
       state: restarted